### ISSUE TITLE
ib_insync with Tkinter: "RuntimeError: There is no current event loop in thread"

### ISSUE THREAD

**Issue by mcandar** [erdewit/ib_insync#103]
I am working on a **Tkinter** GUI that utilizes IB API via **ib_insync** as a data source.

After a button click, I try to run **ib_insync** in a thread to regularly obtain _option chain_ of a specific asset.

I have written a class for this Tkinter app and following code block includes the methods that I invoke **ib_insync**, with another class.

```
    self.connection = IBData()
    def obtain_option_chain(self):
#        asyncio.set_event_loop(asyncio.new_event_loop())
        while continueOptionChain:
            try:
                self.connection.req_underlying()
                self.connection.req_chain_summary()
                self.connection.init_option_chain()
                self.connection.req_option_chain()
            except Exception:
                print(traceback.format_exc())
            time.sleep(15)
            
    def option_chain_start(self):
        global continueOptionChain
        continueOptionChain = True
        try:
            threading.Thread(target=self.obtain_option_chain).start()
        except Exception:
            print(traceback.format_exc())
        
    def run(self):
        if self.connection.sess.isConnected():
            self.option_chain_start()
        else:
            print("Not connected!")
```

However, I get the following error inside `self.connection.req_underlying()`
```
Traceback (most recent call last):
  File "<ipython-input-8-d7e328037dc8>", line 396, in obtain_option_chain
    self.connection.req_underlying()
  File "<ipython-input-1-8babd49f3586>", line 82, in req_underlying
    self.sess.qualifyContracts(self.underlying) # fills in the missing fields, inplace
  File "/anaconda3/envs/others/lib/python3.6/site-packages/ib_insync/ib.py", line 457, in qualifyContracts
    return self._run(self.qualifyContractsAsync(*contracts))
  File "/anaconda3/envs/others/lib/python3.6/site-packages/ib_insync/ib.py", line 236, in _run
    return util.run(*awaitables, timeout=self.RequestTimeout)
  File "/anaconda3/envs/others/lib/python3.6/site-packages/ib_insync/util.py", line 229, in run
    loop = asyncio.get_event_loop()
  File "/anaconda3/envs/others/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/anaconda3/envs/others/lib/python3.6/asyncio/events.py", line 602, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-5'.
```

The method and class I mentioned above is simply:
```
class IBData():
    def __init__(self,host='127.0.0.1',port=4002, clientId=101,**kwargs):
        util.startLoop()
        self.sess = IB()
        self.sess.connect(host,port,clientId)
    def req_underlying(self):
        self.underlying = Stock('SPXS', 'NYSE','USD')
        self.sess.qualifyContracts(self.underlying)
# (... and some other methods too ...)
```

As a final note, I tried `asyncio.set_event_loop(asyncio.new_event_loop())` that could be seen as commented out, and get no error but `qualifyContracts` did not return anything even if I have waited tens of minutes.

I couldn't figure out where I am missing. Any clues?

**Comment by erdewit** [comment]
The multithreading is not used properly here. I would suggest to forego it altogether.
