### ISSUE TITLE
Timeout after being disconnected

### ISSUE THREAD

**Issue by semigodking** [erdewit/ib_insync#118]
Hi,
I noticed that IB gets timeout event after it is disconnected. I am wondering if this is designed behavior or a bug. Meanwhile, passing ``timeout=None`` to IB.connect causes IB freeze when connection fails. Not sure if this is a bug.

This is code and output. 
```
>>> logger=logging.getLogger().setLevel(logging.DEBUG)
>>> ib.connect(host="127.0.0.1", port=12345, timeout=2)
INFO:ib_insync.client:Connecting to 127.0.0.1:12345 with clientId 1...
DEBUG:root:139842985936264 connState: 0 -> 1
INFO:ib_insync.client:Connected
DEBUG:ib_insync.connection:>>> ,,,      v100..139
DEBUG:root:139842985936264 isConn: 1
INFO:ib_insync.client:Disconnected
DEBUG:root:139842985936264 connState: None -> 0
DEBUG:root:139842985936264 connState: None -> 0
ERROR:ib_insync.client:API connection failed: TimeoutError()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/rqalpha/venv/lib/python3.6/site-packages/ib_insync/ib.py", line 202, in connect
    self.run(self.connectAsync(host, port, clientId, timeout))
  File "/home/ubuntu/rqalpha/venv/lib/python3.6/site-packages/ib_insync/util.py", line 241, in run
    result = syncAwait(future)
  File "/home/ubuntu/rqalpha/venv/lib/python3.6/site-packages/ib_insync/util.py", line 335, in syncAwait
    result = loop.run_until_complete(future)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/ubuntu/rqalpha/venv/lib/python3.6/site-packages/ib_insync/ib.py", line 1155, in connectAsync
    await self.client.connectAsync(host, port, clientId, timeout)
  File "/home/ubuntu/rqalpha/venv/lib/python3.6/site-packages/ib_insync/client.py", line 163, in connectAsync
    self.conn.connect(), self._readyEvent.wait()), timeout)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
>>> ib.connect(host="127.0.0.1", port=12345, timeout=None)
INFO:ib_insync.client:Connecting to 127.0.0.1:12345 with clientId 1...
DEBUG:root:139842985936264 connState: 0 -> 1
INFO:ib_insync.client:Connected
DEBUG:ib_insync.connection:>>> ,,,      v100..139
DEBUG:root:139842985936264 isConn: 1
INFO:ib_insync.client:Disconnected
DEBUG:root:139842985936264 connState: None -> 0
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/rqalpha/venv/lib/python3.6/site-packages/ib_insync/ib.py", line 202, in connect
    self.run(self.connectAsync(host, port, clientId, timeout))
  File "/home/ubuntu/rqalpha/venv/lib/python3.6/site-packages/ib_insync/util.py", line 241, in run
    result = syncAwait(future)
  File "/home/ubuntu/rqalpha/venv/lib/python3.6/site-packages/ib_insync/util.py", line 335, in syncAwait
    result = loop.run_until_complete(future)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1390, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
>>>
```
Please be noted that I use code below to simulate immediate disconnection from IB GW.

``` python
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM, socket.IPPROTO_TCP)
s.bind(("127.0.0.1", 12345))
s.listen()
while True:
   client, addr = s.accept()
   client.close()

```

**Comment by semigodking** [comment]
BTW, when i exit from python shell running the test script above, I got the following logs. Looks like CancelledError was not properly handled.
```
ERROR:asyncio:_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
concurrent.futures._base.CancelledError
ERROR:asyncio:_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
concurrent.futures._base.CancelledError
ERROR:asyncio:_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
concurrent.futures._base.CancelledError
DEBUG:root:139842985936264 isConn: 0

```

**Comment by erdewit** [comment]
Socket connection != API connection. It seems you are cutting the socket connection during the API connect, what you get then is a timeout error for the API connect.

The CancelledError is harmless (it's a consequence of a normal cancellation).

**Comment by semigodking** [comment]
Thank you! That makes sense.
