### ISSUE TITLE
qualifyContracts doesn't accept List

### ISSUE THREAD

**Issue by yehoshuadimarsky** [erdewit/ib_insync#119]
Per the [API docs](https://rawgit.com/erdewit/ib_insync/master/docs/html/api.html#ib_insync.ib.IB.qualifyContracts), the `IB.qualifyContracts()` is supposed to accept a `List[ib_insync.contract.Contract]`, but when I pass a `List` it gives me an error, only works on individual items. See snippet below, I created a `List` of `Contracts` by getting it from my portfolio:

```
In [2]: from ib_insync import util, IB

In [3]: util.startLoop()

In [4]: ib = IB()
   ...: ib.connect(clientId=3)
Out[4]: <IB connected to 127.0.0.1:7497 clientId=3>

In [5]: con_list = util.df(ib.portfolio()).loc[:,'contract'].tolist()

In [6]: con_list
Out[6]: 
[Stock(conId=309221236, symbol='ERY', right='0', primaryExchange='ARCA', currency='USD', localSymbol='ERY', tradingClass='ERY'),
 Stock(conId=202915596, symbol='FAZ', right='0', primaryExchange='ARCA', currency='USD', localSymbol='FAZ', tradingClass='FAZ'),
 Stock(conId=202915551, symbol='TZA', right='0', primaryExchange='ARCA', currency='USD', localSymbol='TZA', tradingClass='TZA')]

In [7]: ib.qualifyContracts(con_list)
Traceback (most recent call last):

  File "<ipython-input-7-79ce5df6855e>", line 1, in <module>
    ib.qualifyContracts(con_list)

  File "C:\Users\JoshDimarsky\AppData\Local\Continuum\miniconda3\envs\ibapi\lib\site-packages\ib_insync\ib.py", line 512, in qualifyContracts
    return self._run(self.qualifyContractsAsync(*contracts))

  File "C:\Users\JoshDimarsky\AppData\Local\Continuum\miniconda3\envs\ibapi\lib\site-packages\ib_insync\ib.py", line 257, in _run
    return util.run(*awaitables, timeout=self.RequestTimeout)

  File "C:\Users\JoshDimarsky\AppData\Local\Continuum\miniconda3\envs\ibapi\lib\site-packages\ib_insync\util.py", line 236, in run
    result = loop.run_until_complete(future)

  File "C:\Users\JoshDimarsky\AppData\Local\Continuum\miniconda3\envs\ibapi\lib\site-packages\nest_asyncio.py", line 59, in run_until_complete
    return f.result()

  File "C:\Users\JoshDimarsky\AppData\Local\Continuum\miniconda3\envs\ibapi\lib\asyncio\tasks.py", line 180, in _step
    result = coro.send(None)

  File "C:\Users\JoshDimarsky\AppData\Local\Continuum\miniconda3\envs\ibapi\lib\site-packages\ib_insync\ib.py", line 1556, in qualifyContractsAsync
    *(self.reqContractDetailsAsync(c) for c in contracts))

  File "C:\Users\JoshDimarsky\AppData\Local\Continuum\miniconda3\envs\ibapi\lib\site-packages\ib_insync\ib.py", line 1556, in <genexpr>
    *(self.reqContractDetailsAsync(c) for c in contracts))

  File "C:\Users\JoshDimarsky\AppData\Local\Continuum\miniconda3\envs\ibapi\lib\site-packages\ib_insync\ib.py", line 1647, in reqContractDetailsAsync
    self.client.reqContractDetails(reqId, contract)

  File "C:\TWS API\source\pythonclient\ibapi\client.py", line 1942, in reqContractDetails
    flds += [make_field(contract.conId), # srv v37 and above

AttributeError: 'list' object has no attribute 'conId'

In [8]: ib.qualifyContracts(con_list[0])
Out[8]: [Stock(conId=309221236, symbol='ERY', exchange='SMART', primaryExchange='ARCA', currency='USD', localSymbol='ERY', tradingClass='ERY')]
```

**Comment by hadrianl** [comment]
ib.qualifyContracts(*con_list)

**Comment by erdewit** [comment]
What hadrianl said, unpack the list with *.

**Comment by yehoshuadimarsky** [comment]
Got it oops, thanks.
