### ISSUE TITLE
AttributeError: 'Order' object has no attribute 'algoParamsCount'

### ISSUE THREAD

**Issue by dyus1983** [erdewit/ib_insync#22]
Hello,
I get AttributeError: 'Order' object has no attribute 'algoParamsCount', after I submit an adaptive algo order, which is contructed (following the instructions at https://interactivebrokers.github.io/tws-api/ibalgos.html#gsc.tab=0) as:
```
def MarketOrder(**kwargs):
    order = Order(orderType='MKT', **kwargs)

    return order

def AdaptiveMarketOrder(priority='Normal', **kwargs):
    priority = priority.capitalize()
    valid_priorities = ['Critical', 'Urgent', 'Normal', 'Patient']
    assert priority in valid_priorities, "Invalid priority. Should be in %s." % (valid_priorities)

    order = MarketOrder(**kwargs)
    order.algoStrategy = "Adaptive"
    order.algoParams = []
    adaptivePriority = ib_insync.objects.TagValue('adaptivePriority', priority)
    order.algoParams.append(adaptivePriority)

    return order

class Data:
...
def order(self, contract: ib_insync.Contract, amount: int, style: ib_insync.order.Order, transmit=False):
        order = style
        order.account = self.data.account
        order.action = ('BUY' if amount >= 0 else 'SELL')
        order.totalQuantity = abs(int(amount))
        order.transmit = transmit

        trade = self.broker.placeOrder(contract, order)

        return trade.order
...

data.order(gld, 100, style=AdaptiveMarketOrder(priority='Normal'), transmit=True)

```
The full traceback:
```
2017-11-15 02:38:41,724 ib_insync.client ERROR Decode failed
Traceback (most recent call last):
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ib_insync/client.py", line 223, in _onSocketHasData
    self._decode(fields)
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ib_insync/client.py", line 378, in _decode
    self.decoder.interpret(fields)
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ibapi-9.73.2-py3.6.egg/ibapi/decoder.py", line 1154, in interpret
    handleInfo.processMeth(self, iter(fields))
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ibapi-9.73.2-py3.6.egg/ibapi/decoder.py", line 413, in processOpenOrder
    self.wrapper.openOrder(order.orderId, contract, order, orderState)
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ib_insync/wrapper.py", line 192, in openOrder
    order = Order(**order.__dict__)
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ib_insync/objects.py", line 53, in __init__
    setattr(self, k, v)
AttributeError: 'Order' object has no attribute 'algoParamsCount'
2017-11-15 02:38:41,725 ib_insync.wrapper INFO orderStatus: Trade(contract=Contract(conId=51529211, symbol='GLD', secType='STK', exchange='SMART', primaryExchange='ARCA', currency='USD', localSymbol='GLD', tradingClass='GLD'), order=Order(orderId=149, action='SELL', totalQuantity=100, orderType='MKT', account='U1744631', algoStrategy='Adaptive', algoParams=[TagValue(tag='adaptivePriority', value='Normal')]), orderStatus=OrderStatus(status='Submitted', remaining=100.0, permId=1483409048, clientId=34), fills=[], log=[TradeLogEntry(time=datetime.datetime(2017, 11, 14, 20, 38, 41, 392626, tzinfo=datetime.timezone.utc), status='PendingSubmit', message=''), TradeLogEntry(time=datetime.datetime(2017, 11, 14, 20, 38, 41, 723600, tzinfo=datetime.timezone.utc), status='Submitted', message='')])
2017-11-15 02:38:57,046 ib_insync.wrapper INFO position: Position(account='U1744631', contract=Contract(conId=51529211, symbol='GLD', secType='STK', exchange='ARCA', currency='USD', localSymbol='GLD', tradingClass='GLD'), position=524.0, avgCost=121.82631555)
2017-11-15 02:38:57,047 ib_insync.wrapper INFO execDetails: Fill(contract=Contract(conId=51529211, symbol='GLD', secType='STK', exchange='SMART', primaryExchange='ARCA', currency='USD', localSymbol='GLD', tradingClass='GLD'), execution=Execution(execId='00013911.5a0ad7f2.01.01', time='20171115  02:38:56', acctNumber='U1744631', exchange='ISLAND', side='SLD', shares=100.0, price=121.71, permId=1483409048, clientId=34, orderId=149, cumQty=100.0, avgPrice=121.71), commissionReport=CommissionReport(), time=datetime.datetime(2017, 11, 14, 20, 38, 57, 47655, tzinfo=datetime.timezone.utc))
2017-11-15 02:38:57,048 ib_insync.client ERROR Decode failed
Traceback (most recent call last):
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ib_insync/client.py", line 223, in _onSocketHasData
    self._decode(fields)
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ib_insync/client.py", line 378, in _decode
    self.decoder.interpret(fields)
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ibapi-9.73.2-py3.6.egg/ibapi/decoder.py", line 1154, in interpret
    handleInfo.processMeth(self, iter(fields))
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ibapi-9.73.2-py3.6.egg/ibapi/decoder.py", line 413, in processOpenOrder
    self.wrapper.openOrder(order.orderId, contract, order, orderState)
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ib_insync/wrapper.py", line 192, in openOrder
    order = Order(**order.__dict__)
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ib_insync/objects.py", line 53, in __init__
    setattr(self, k, v)
AttributeError: 'Order' object has no attribute 'algoParamsCount'
2017-11-15 02:38:57,049 ib_insync.wrapper INFO orderStatus: Trade(contract=Contract(conId=51529211, symbol='GLD', secType='STK', exchange='SMART', primaryExchange='ARCA', currency='USD', localSymbol='GLD', tradingClass='GLD'), order=Order(orderId=149, action='SELL', totalQuantity=100, orderType='MKT', account='U1744631', algoStrategy='Adaptive', algoParams=[TagValue(tag='adaptivePriority', value='Normal')]), orderStatus=OrderStatus(status='Filled', filled=100.0, avgFillPrice=121.71, permId=1483409048, lastFillPrice=121.71, clientId=34), fills=[Fill(contract=Contract(conId=51529211, symbol='GLD', secType='STK', exchange='SMART', primaryExchange='ARCA', currency='USD', localSymbol='GLD', tradingClass='GLD'), execution=Execution(execId='00013911.5a0ad7f2.01.01', time='20171115  02:38:56', acctNumber='U1744631', exchange='ISLAND', side='SLD', shares=100.0, price=121.71, permId=1483409048, clientId=34, orderId=149, cumQty=100.0, avgPrice=121.71), commissionReport=CommissionReport(), time=datetime.datetime(2017, 11, 14, 20, 38, 57, 47655, tzinfo=datetime.timezone.utc))], log=[TradeLogEntry(time=datetime.datetime(2017, 11, 14, 20, 38, 41, 392626, tzinfo=datetime.timezone.utc), status='PendingSubmit', message=''), TradeLogEntry(time=datetime.datetime(2017, 11, 14, 20, 38, 41, 723600, tzinfo=datetime.timezone.utc), status='Submitted', message=''), TradeLogEntry(time=datetime.datetime(2017, 11, 14, 20, 38, 57, 47655, tzinfo=datetime.timezone.utc), status='Submitted', message='Fill 100.0@121.71'), TradeLogEntry(time=datetime.datetime(2017, 11, 14, 20, 38, 57, 47655, tzinfo=datetime.timezone.utc), status='Filled', message='')])
2017-11-15 02:38:57,051 ib_insync.client ERROR Decode failed
Traceback (most recent call last):
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ib_insync/client.py", line 223, in _onSocketHasData
    self._decode(fields)
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ib_insync/client.py", line 378, in _decode
    self.decoder.interpret(fields)
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ibapi-9.73.2-py3.6.egg/ibapi/decoder.py", line 1154, in interpret
    handleInfo.processMeth(self, iter(fields))
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ibapi-9.73.2-py3.6.egg/ibapi/decoder.py", line 413, in processOpenOrder
    self.wrapper.openOrder(order.orderId, contract, order, orderState)
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ib_insync/wrapper.py", line 192, in openOrder
    order = Order(**order.__dict__)
  File "/home/dias/anaconda3/lib/python3.6/site-packages/ib_insync/objects.py", line 53, in __init__
    setattr(self, k, v)
AttributeError: 'Order' object has no attribute 'algoParamsCount'
```
The order actually gets filled, but this error is disturbing. 
Could you help?

**Comment by erdewit** [comment]
Thanks for the very complete bug report - it contains everything to track the bug down. The issue is with decoder.py from the ibapi package; it's using ``algoParamsCount`` as a property of ``Order`` although it shouldn't. I've just uploaded version 0.8.10 of ib_insync that deals with this issue.

It can be installed with:

``pip3 install -U ib_insync``

**Comment by dyus1983** [comment]
Thank you for the support!
