### ISSUE TITLE
AttributeError: module 'ibapi.contract' has no attribute 'UnderComp'

### ISSUE THREAD

**Issue by nickvin** [erdewit/ib_insync#233]
Can't get past this error:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\Nicolas Vincent\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\193.6911.25\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Nicolas Vincent\Anaconda3\envs\IB\lib\site-packages\ib_insync\__init__.py", line 20, in <module>
    from .objects import *
  File "C:\Users\Nicolas Vincent\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\193.6911.25\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Nicolas Vincent\Anaconda3\envs\IB\lib\site-packages\ib_insync\objects.py", line 147, in <module>
    class UnderComp(Object):
  File "C:\Users\Nicolas Vincent\Anaconda3\envs\IB\lib\site-packages\ib_insync\objects.py", line 148, in UnderComp
    defaults = ibapi.contract.UnderComp().__dict__
AttributeError: module 'ibapi.contract' has no attribute 'UnderComp'

**Comment by goodboy** [comment]
@nickvin bruv, what version you on?

10 bucks [it ain't the right one](https://github.com/erdewit/ib_insync/blob/master/ib_insync/objects.py#L147) :wink:

Also, you're doxxing youself and/or your friend:
```File "C:\Users\Nicolas Vincent\```

If you [read the docs](https://github.com/erdewit/ib_insync#installation) you'd see `ibapi` ain't used no more :smile_cat:

**Comment by nickvin** [comment]
Wow, thx for the quick reply hombre
I'm running 0.8.15... the one pip picked from the internets
As for ibapi, I believe it just installed with the IB API. Do I have to
remove it?
Apologies if I seem retarded, this is all very new to me.

Cheers

**Comment by goodboy** [comment]
@nickvin no problem, I'm a watcher (and hopefully soon to be some kinda contributor).

Yeah looking at `git log` I see some `v0.9.59` in the notes on ef9ad0a.
If you look at the latest code (usually the first thing I do when I get weird errors like this) you can see it's pretty much not at all the same. Might want to check your pips and/or internets. Maybe try just cloning the repo and porting your code from that. 

RE: 
> As for ibapi, I believe it just installed with the IB API. Do I have toremove it?

Prolly. I don't know exactly but I do know that I was happy I don't have to use IB's code base any more with `ib_insync` :smile:

**Comment by nickvin** [comment]
Sweet!
Installed the latest version and all is good!
Thx for your help, it's much appreciated!
