### ISSUE TITLE
Qualifycontracts() not working since last update

### ISSUE THREAD

**Issue by tradefish** [erdewit/ib_insync#257]
Hi Ewald, my TWS has made an update today and the instruction Qualifycontracts() is not working anymore. For example:

spx = Index('SPX', 'CBOE')
ib.qualifyContracts(spx)

Decode failed
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ib_insync\client.py", line 279, in _onSocketHasData
    self._decode(fields)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ib_insync\client.py", line 380, in _decode
    self.decoder.interpret(fields)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ibapi\decoder.py", line 1425, in interpret
    handleInfo.processMeth(self, iter(fields))
  File "C:\ProgramData\Anaconda3\lib\site-packages\ibapi\decoder.py", line 526, in processContractDataMsg
    contract.timeZoneId = decode(str, fields)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ibapi\utils.py", line 72, in decode
    return s.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 13: invalid continuation byte
Unknown contract: Index(symbol='SPX', exchange='CBOE')

I've also tried with stocks, and it's the same....

Thank you,

Raul

**Comment by tradefish** [comment]
Hi again Ewald, it seems that the problem is only with the TWS, if I tray with de IB Gateway, everything is correct, so it seems it must be something related with the latest TWS update....
I'll check later again with the TWS, to see if the problem is still there.....

**Comment by erdewit** [comment]
The error comes from the bowels of ``ibapi``, which is not used any more in ib_insync. You might want to update ib_inysnc to a newer version.

**Comment by tradefish** [comment]
Ok, thank you!!
________________________________
