### ISSUE TITLE
import is not working while using PyCharm

### ISSUE THREAD

**Issue by alexa-ai** [erdewit/ib_insync#334]
`from ib_insync import *`
`ib = IB()`

This works fine in Google colab notebook. However, when running this in PyCharm, it does not seem to import all. PyCharm shows IB not defined. None of the classes from ib_insync can be referred. I tried `from ib_insync import IB` as well. It  did not make any difference.

**Comment by erdewit** [comment]
Probably the same as #335.

**Comment by alexa-ai** [comment]
Thanks @erdewit . Yes, I had the local file name as ib_insync.py. I saved the file as different name. Still, get the same issue, 

`[2021-02-08 22:16:51,645] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "c:\users\ra_000\pycharmprojects\pythonproject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\ra_000\pycharmprojects\pythonproject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\ra_000\pycharmprojects\pythonproject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ra_000\pycharmprojects\pythonproject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\ra_000\pycharmprojects\pythonproject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\ra_000\pycharmprojects\pythonproject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ra_000\PycharmProjects\pythonProject\ib_app_v4.py", line 11, in hello_world
    ib = IB()
NameError: name 'IB' is not defined
127.0.0.1 - - [08/Feb/2021 22:16:51] "←[35m←[1mGET / HTTP/1.1←[0m" 500 -
`

**Comment by erdewit** [comment]
Try removing the ``__pycache__`` directory.

**Comment by alexa-ai** [comment]
Thanks. Now, I got into issue as in https://github.com/erdewit/ib_insync/issues/33.

**Comment by alexa-ai** [comment]
If anyone has the same issue with PyCharm, and if you use Flask: See https://github.com/erdewit/ib_insync/issues/18#issuecomment-333095362
