### ISSUE TITLE
RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by rundef** [erdewit/ib_insync#340]
Hello,

First of all, thank you for your work !

I'm trying to call `reqMktData` within an event handler callback function and an exception is thrown `RuntimeError: This event loop is already running`.

```python
from ib_insync import *

# Do i need to do this ?
#util.patchAsyncio()

def get_mkt_price(contract):
    tick = ib.reqMktData(contract, '318')
    ib.sleep(2)
    print('tick')
    print(tick)
    return tick.last

def on_new_bar(bars, has_new_bar):
    if has_new_bar:
        price = get_mkt_price(contract)

ib = IB()
ib.connect('127.0.0.1', 7497, clientId=1)

contract = Stock('SPY', 'SMART', 'USD')
ib.qualifyContracts(contract)

data = ib.reqHistoricalData(
    contract,
    '',
    barSizeSetting='5 mins',
    useRTH=True,
    keepUpToDate=True,
    durationStr='1 D',
    whatToShow='TRADES'
)
data.updateEvent += on_new_bar

ib.run()
```

```
Traceback (most recent call last):
  File "/home/mickael/anaconda3/envs/algotrading/lib/python3.9/site-packages/eventkit/event.py", line 181, in emit
    func(*args)
  File "/home/mickael/work/code/ml-finance/atf/testloop.py", line 16, in on_new_bar
    price = get_mkt_price(contract)
  File "/home/mickael/work/code/ml-finance/atf/testloop.py", line 9, in get_mkt_price
    ib.sleep(2)
  File "/home/mickael/anaconda3/envs/algotrading/lib/python3.9/site-packages/ib_insync/util.py", line 368, in sleep
    run(asyncio.sleep(secs))
  File "/home/mickael/anaconda3/envs/algotrading/lib/python3.9/site-packages/ib_insync/util.py", line 322, in run
    result = loop.run_until_complete(task)
  File "/home/mickael/anaconda3/envs/algotrading/lib/python3.9/asyncio/base_events.py", line 618, in run_until_complete
    self._check_running()
  File "/home/mickael/anaconda3/envs/algotrading/lib/python3.9/asyncio/base_events.py", line 578, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

If I uncomment `util.patchAsyncio()` at the beginning of the script, I get the following exception instead:

```
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/home/mickael/anaconda3/envs/algotrading/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <Context object at 0x7f4b815dfa00> is already entered
```

I'm using `ib-insync v0.9.64` and `nest-asyncio 1.5.1`.

Am I missing something ?

**Comment by erdewit** [comment]
``ib.sleep`` or other blocking requests should not be used in an event handler. It can run with older versions of nest_asyncio (v1.4.x)  but this is not recommended.

Also note that ``reqMktData`` should be called only once (obviating the need for ib.sleep), and that generic tick 318 is not yet supported.
