### ISSUE TITLE
disconnect() doesn't appear to actually release the client session and id on IB GW until program exits

### ISSUE THREAD

**Issue by BoogeyOff** [erdewit/ib_insync#360]
The simplest most distilled down way to reproduce the issue is with the following program which simply connects and disconnects to a running GW instance.

```
from ib_insync import *
if __name__ == '__main__':

    ib = IB()
    ib.connect('localhost', 4001, clientId=1)
    ib.disconnect()
    input('Should be Disconnected now')
```
When you get to the input() call, run the same program from a different shell. Here's the output:
```
Peer closed connection
clientId 1 already in use?
API connection failed: TimeoutError()
Traceback (most recent call last):
  File "C:\Users\Dima\anaconda3\envs\py3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Dima\anaconda3\envs\py3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Dima\Python\JusTrade\test\test_ib.py", line 269, in <module>
    ib.connect('localhost', 4001, clientId=1)
  File "C:\Users\Dima\anaconda3\envs\py3\lib\site-packages\ib_insync\ib.py", line 272, in connect
    host, port, clientId, timeout, readonly, account))
  File "C:\Users\Dima\anaconda3\envs\py3\lib\site-packages\ib_insync\ib.py", line 310, in _run
    return util.run(*awaitables, timeout=self.RequestTimeout)
  File "C:\Users\Dima\anaconda3\envs\py3\lib\site-packages\ib_insync\util.py", line 322, in run
    result = loop.run_until_complete(task)
  File "C:\Users\Dima\anaconda3\envs\py3\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\Dima\anaconda3\envs\py3\lib\site-packages\ib_insync\ib.py", line 1631, in connectAsync
    host, port, clientId, timeout or None)
  File "C:\Users\Dima\anaconda3\envs\py3\lib\site-packages\ib_insync\client.py", line 223, in connectAsync
    await asyncio.wait_for(connect(), timeout or None)
  File "C:\Users\Dima\anaconda3\envs\py3\lib\asyncio\tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

The same is also visible on the GW application - the 'Client 1' tab stays light grey (not the disconnected dark colour) until the first python app exits.

Am I missing something obvious here?

Running IB GW version 978 on Windows. Same outcome whether IB GW launched from IBC or manually.

**Comment by BoogeyOff** [comment]
Tested the same thing with the native IBAPI and that seems to work correctly. the GW drops the client ID after the disconnect call, which is weird because their EClient disconnect looks virtually identical to ib_insync's as follows:
```
    def disconnect(self):
        """Call this function to terminate the connections with TWS.
        Calling this function does not cancel orders that have already been
        sent."""

        self.setConnState(EClient.DISCONNECTED)
        if self.conn is not None:
            logger.info("disconnecting")
            self.conn.disconnect()
            self.wrapper.connectionClosed()
            self.reset()
```

**Comment by BoogeyOff** [comment]
yep, looks like it's asyncio messing with things. I've managed to get a work-around working by declaring a new async dicsonnect2 routine that calls disconnect, and getting the event loop to run it until completion. this releases the connection on the GW side. full code:

```
from ib_insync import *

class IB2(IB):
    async def disconnect2(self):
        self.disconnect()
        
if __name__ == '__main__':
    asyncio.set_event_loop(asyncio.ProactorEventLoop())
    event_loop = asyncio.new_event_loop()
    asyncio.set_event_loop(event_loop)
    ib = IB2()
    ib.connect('localhost', 4001, clientId=1)
    event_loop.run_until_complete(ib.disconnect2())
    input('Should be Disconnected now')
```
    
Might be worth reworking disconnect along these lines.

**Comment by erdewit** [comment]
Thanks for the bug report. There have been multiple reports like this over the years, but this time I can actually reproduce the issue using your first snippet. The solution is to write an explicit EOF  before closing the socket connection.
