### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 7496)

### ISSUE THREAD

**Issue by kenno94-IK** [erdewit/ib_insync#395]
I am unable to connect to the API. What could be causing this problem?

API connection failed: ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 7496)")
Make sure API port on TWS/IBG is open
Traceback (most recent call last):
  File "request_data.py", line 5, in <module>
    ib.connect('127.0.0.1', 7496, clientId=1)
  File "/home/ian/.local/lib/python3.8/site-packages/ib_insync/ib.py", line 271, in connect
    return self._run(self.connectAsync(
  File "/home/ian/.local/lib/python3.8/site-packages/ib_insync/ib.py", line 310, in _run
    return util.run(*awaitables, timeout=self.RequestTimeout)
  File "/home/ian/.local/lib/python3.8/site-packages/ib_insync/util.py", line 322, in run
    result = loop.run_until_complete(task)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ian/.local/lib/python3.8/site-packages/ib_insync/ib.py", line 1626, in connectAsync
    await self.client.connectAsync(host, port, clientId, timeout)
  File "/home/ian/.local/lib/python3.8/site-packages/ib_insync/client.py", line 212, in connectAsync
    await asyncio.wait_for(self.conn.connectAsync(host, port), timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/home/ian/.local/lib/python3.8/site-packages/ib_insync/connection.py", line 37, in connectAsync
    self.transport, _ = await loop.create_connection(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 526, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 7496)

**Comment by erdewit** [comment]
Probably the wrong port number, or port is not open.

**Comment by kenno94-IK** [comment]
Hi Erdewit,

So I had double-checked the port number and it is correct. How would I check if the port is open or not? Also, could there be a permissions issue? Thank you.

**Comment by LaurentRDC** [comment]
FYI, I had the same error. The trick was to activate this option in API settings :

![image](https://user-images.githubusercontent.com/16210338/152062888-fcd7b96d-a25b-4589-b941-c13fd4462138.png)
