### ISSUE TITLE
TypeError: An asyncio.Future, a coroutine or an awaitable is required

### ISSUE THREAD

**Issue by jbecic** [erdewit/ib_insync#408]
I am new to ib_insync, I have been trying to run a simple script. I started having issues with "Error: This event loop is already running" but nest_asyncio seems to have solved it. However, there is now an asyncio issue, I have no idea what asyncio is or how to use it. The script starts out fine, prints the value that I am looking for but then throws this error. I am using python 3.8.12, mac OS. See script and error below:

`from ib_insync import *
import nest_asyncio
nest_asyncio.apply()

ib = IB()
ib.connect('127.0.0.1', 7497, clientId=1)

accVvals = float([v.value for v in ib.accountValues() if v.tag == 'NetLiquidation' and v.currency == 'USD'][0])
print(accVvals)

ib.disconnect()`

`1183574.12

[SpyderKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jasminbecic/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder_kernels/comms/frontendcomm.py", line 164, in poll_one
    asyncio.run(handler(out_stream, ident, msg))
  File "/Users/jasminbecic/opt/anaconda3/envs/py38/lib/python3.8/site-packages/nest_asyncio.py", line 32, in run
    return loop.run_until_complete(future)
  File "/Users/jasminbecic/opt/anaconda3/envs/py38/lib/python3.8/site-packages/nest_asyncio.py", line 60, in run_until_complete
    f = asyncio.ensure_future(future, loop=self)
  File "/Users/jasminbecic/opt/anaconda3/envs/py38/lib/python3.8/asyncio/tasks.py", line 684, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
[SpyderKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/jasminbecic/opt/anaconda3/envs/py38/lib/python3.8/site-packages/spyder_kernels/comms/frontendcomm.py", line 164, in poll_one
    asyncio.run(handler(out_stream, ident, msg))
  File "/Users/jasminbecic/opt/anaconda3/envs/py38/lib/python3.8/site-packages/nest_asyncio.py", line 32, in run
    return loop.run_until_complete(future)
  File "/Users/jasminbecic/opt/anaconda3/envs/py38/lib/python3.8/site-packages/nest_asyncio.py", line 60, in run_until_complete
    f = asyncio.ensure_future(future, loop=self)
  File "/Users/jasminbecic/opt/anaconda3/envs/py38/lib/python3.8/asyncio/tasks.py", line 684, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required`

**Comment by erdewit** [comment]
Judging from the stack trace, this seems to be a bug in Spyder.

It might be possible to circumvent by placing (after the nest_asyncio code):

```python
import asyncio
del asyncio.run
```
