### ISSUE TITLE
Exception parsing a contract value 

### ISSUE THREAD

**Issue by ravijagan** [erdewit/ib_insync#428]
09:55:03,128 ib_insync.Decoder ERROR Error handling fields: ['1', '6', '163635', '4', '4594.45', '', '0']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ib_insync/decoder.py", line 193, in interpret
    handler(fields)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ib_insync/decoder.py", line 216, in priceSizeTick
    int(reqId), int(tickType), float(price), float(size))
ValueError: could not convert string to float: ''
09:55:03,129 ib_insync.Decoder ERROR Error handling fields: ['1', '6', '163635', '4', '4593.99', '', '0']
Traceback (most recent call last):
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ib_insync/decoder.py", line 193, in interpret
    handler(fields)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ib_insync/decoder.py", line 216, in priceSizeTick
    int(reqId), int(tickType), float(price), float(size))
ValueError: could not convert string to float: ''

**Comment by ravijagan** [comment]
This seems to reliably reproduce the error . Havent seen this before though 
>>con
Index(symbol='SPX', exchange='CBOE')
>>ib.qualifyContracts(con)
[Index(conId=416904, symbol='SPX', exchange='CBOE', currency='USD', localSymbol='SPX')]

**Comment by erdewit** [comment]
The exception is logged but not thrown, and everything keeps running. This is the intended way to handle the case were IB sends bogus data.

The index data works for me btw:

```
Ticker(contract=Index(conId=416904, symbol='SPX', exchange='CBOE', currency='USD', localSymbol='SPX'), time=datetime.datetime(2022, 1, 18, 18, 36, 10, 646012, tzinfo=datetime.timezone.utc), last=4579.45, lastSize=0.0, prevLast=4579.53, high=4632.24, low=4569.82, close=4662.85, ticks=[TickData(time=datetime.datetime(2022, 1, 18, 18, 36, 10, 646012, tzinfo=datetime.timezone.utc), tickType=4, price=4579.53, size=0.0), TickData(time=datetime.datetime(2022, 1, 18, 18, 36, 10, 646012, tzinfo=datetime.timezone.utc), tickType=4, price=4579.45, size=0.0)])
```
