### ISSUE TITLE
Pandas TZ aware timestamp conversion triggers exception in formatIBDatetime()

### ISSUE THREAD

**Issue by mdelvaux** [erdewit/ib_insync#441]
Passing a pandas TZ aware timestamp as argument endDateTime of reqHistoricalData() triggers an exception.  This is a pandas issue where the signature of astimezone differs between pandas, where it is simply astimezone(tz), and datetime.datetime, where it is astimezone(tz=None) even if a pandas timestamp indicates that is an instance of datetime.datetime.  The solution seems simple enough that it may be worthwhile to modify ib_insync code: explicitly pass None to astimezone() when called inside formatIBDatetime().  This was tested locally on my machine and removed the exception.

What triggered this issue is using ibis.util.df(bars) while asking formatDate = 2.  This results in the date column to become a TZ aware pandas timestamp, passing that value back to reqHistoricalData then crashes, the script attached (as a .txt to make github happy) is a fully worked out example to show the only failing case, in particular using the same code with formatDate = 1 has no issue.
[datetime_conversion_issue.py.txt](https://github.com/erdewit/ib_insync/files/8051062/datetime_conversion_issue.py.txt)

That script produces the following output

>>>

A pandas timestamp <class 'pandas._libs.tslibs.timestamps.Timestamp'> is also considered a datetime
isinstance(pd.Timestamp()) returns True
But a pandas timestamp does not support astimezone() with an empty argument list, so formatIBDatetime crashes
Traceback (most recent call last):
  File "D:/docs/upwork/marc_gamma_scalping/code/datetime_conversion_issue.py", line 14, in <module>
    ibis.util.formatIBDatetime(timestamp)
  File "D:\Anaconda3\envs\marc_gamma_scalping\lib\site-packages\ib_insync\util.py", line 508, in formatIBDatetime
    dt = dt.astimezone()
  File "pandas\_libs\tslibs\timestamps.pyx", line 1732, in pandas._libs.tslibs.timestamps.Timestamp.tz_convert
TypeError: tz_convert() takes exactly 2 positional arguments (1 given)
Initial bars, format 1, 34 bars between 2022-02-11 11:00:00 and 2022-02-07 06:30:00, with date type <class 'datetime.datetime'>
Next set via <class 'str'> 20220207 06:30:00, 35 bars ending at 2022-02-04 12:00:00
Next set via <class 'datetime.datetime'> 2022-02-07 06:30:00, 35 bars ending at 2022-02-04 12:00:00
Next set via <class 'str'> 20220207 06:30:00 , 35 bars ending at 2022-02-04 12:00:00
Next set via <class 'pandas._libs.tslibs.timestamps.Timestamp'> 2022-02-07 06:30:00, 35 bars ending at 2022-02-04 12:00:00
Initial bars, format 2, 34 bars between 2022-02-11 19:00:00+00:00 and 2022-02-07 14:30:00+00:00, with date type <class 'datetime.datetime'>
Next set via <class 'str'> 20220207 06:30:00, 35 bars ending at 2022-02-04 20:00:00+00:00
Next set via <class 'datetime.datetime'> 2022-02-07 14:30:00+00:00, 35 bars ending at 2022-02-04 20:00:00+00:00
Next set via <class 'str'> 20220207 14:30:00 UTC, 35 bars ending at 2022-02-04 20:00:00+00:00
<bound method Timestamp.tz_convert of Timestamp('2022-02-07 14:30:00+0000', tz='UTC')>
Next set via <class 'pandas._libs.tslibs.timestamps.Timestamp'> 2022-02-07 06:30:00, 35 bars ending at 2022-02-04 20:00:00+00:00
Hit exception
Traceback (most recent call last):
  File "D:/docs/upwork/marc_gamma_scalping/code/datetime_conversion_issue.py", line 98, in <module>
    bars22_pd = ib.reqHistoricalData(aapl, end2_pd, "1 W", "1 hour", "TRADES", True, formatDate=2)
  File "D:\Anaconda3\envs\marc_gamma_scalping\lib\site-packages\ib_insync\ib.py", line 1048, in reqHistoricalData
    return self._run(
  File "D:\Anaconda3\envs\marc_gamma_scalping\lib\site-packages\ib_insync\ib.py", line 308, in _run
    return util.run(*awaitables, timeout=self.RequestTimeout)
  File "D:\Anaconda3\envs\marc_gamma_scalping\lib\site-packages\ib_insync\util.py", line 332, in run
    result = loop.run_until_complete(task)
  File "D:\Anaconda3\envs\marc_gamma_scalping\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\Anaconda3\envs\marc_gamma_scalping\lib\site-packages\ib_insync\ib.py", line 1857, in reqHistoricalDataAsync
    end = util.formatIBDatetime(endDateTime)
  File "D:\Anaconda3\envs\marc_gamma_scalping\lib\site-packages\ib_insync\util.py", line 508, in formatIBDatetime
    dt = dt.astimezone()
  File "pandas\_libs\tslibs\timestamps.pyx", line 1732, in pandas._libs.tslibs.timestamps.Timestamp.tz_convert
TypeError: tz_convert() takes exactly 2 positional arguments (1 given)

**Comment by erdewit** [comment]
Thank you for the extensive report. I agree that ``astimezone(tz=None)`` is a good way to deal with it and will add that to the code.
