### ISSUE TITLE
Watchdog Issue: Not restarting correctly unless I click on the "I Undesrtand and Accept" window

### ISSUE THREAD

**Issue by Sdoof** [erdewit/ib_insync#448]
Hello 

Thanks so much for puting such a wonderul framework together.

I am running the following code available from the group.io discussion "Watchdog doesnt restart on error 1100 or Gateway shutdown" [https://groups.io/g/insync/topic/29780496](url)

```
from ib_insync import *
import asyncio

asyncio.set_event_loop(asyncio.ProactorEventLoop()) # required on Windows only
util.patchAsyncio()
ib = IB()
ibc = IBC(twsVersion=1012, gateway=False, tradingMode='paper', ibcPath='C:\\IBC', ibcIni='C:\\Users\\XXX\\Documents\\ibc\\config.ini')

watchdog = Watchdog(ibc, ib, port=7490)

def onStartedEvent(watchdog):
    while True:
        cont = Stock('TSLA', 'SMART', 'USD')
        ib.qualifyContracts(cont)
        print(cont)
        ib.sleep(5)

watchdog.startedEvent += onStartedEvent
watchdog.start()
IB.run()
```

This code will only run if I manually click on the window "This is not a brokerage account...Please confirm that you understand..."
Having to click somewhat defeat the purpose of the Watchdog function. I I don t click the following messages get displayed. 

Any chance of getting this resolved?

```
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\asyncio\proactor_events.py", line 141, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
API connection failed: TimeoutError()
Traceback (most recent call last):
  File "C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\ib_insync\ibcontroller.py", line 427, in runAsync
    self.readonly)
  File "C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\ib_insync\ib.py", line 1626, in connectAsync
    await self.client.connectAsync(host, port, clientId, timeout)
  File "C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\site-packages\ib_insync\client.py", line 217, in connectAsync
    await asyncio.wait_for(self.apiStart, timeout)
  File "C:\Users\olivi\AppData\Local\Programs\Python\Python37\lib\asyncio\tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
SUCCESS: The process with PID 11736 (child process of PID 11348) has been terminated.
SUCCESS: The process with PID 11348 (child process of PID 15536) has been terminated.
SUCCESS: The process with PID 5852 (child process of PID 15536) has been terminated.
SUCCESS: The process with PID 6652 (child process of PID 15536) has been terminated.
SUCCESS: The process with PID 19512 (child process of PID 15536) has been terminated.
SUCCESS: The process with PID 972 (child process of PID 15536) has been terminated.
SUCCESS: The process with PID 20284 (child process of PID 15536) has been terminated.
SUCCESS: The process with PID 15536 (child process of PID 15488) has been terminated.
SUCCESS: The process with PID 15488 (child process of PID 7856) has been terminated.
SUCCESS: The process with PID 7856 (child process of PID 11820) has been terminated.
```

**Comment by erdewit** [comment]
I think this is a setting in the IBC project. For me the popup appears also and is then automatically clicked away.
