### ISSUE TITLE
Troubles with auto reconnection

### ISSUE THREAD

**Issue by nkasimova** [erdewit/ib_insync#503]
My program works perfectly all day without problems.
But after finish current trading session (17:00 ET) I see behavior like this:
[UTC+3]
...
23:59:59 - before this moment everything works as expected
00:00:00 - end of the current trading session (it's 17:00 ET)
... bid/ask is -1/-1
00:15:00 - start of a new trading session (it's 17:15 ET)
And from this moment I have a lot of "Error for updateMktDepth".

Can somebody explain step by step how to do auto reconnection in a right way?

Current not working code for reconnection is :
[simplified version]

`  

    SYMBOL = 'EURUSD'
    
    class IBConnectionModule:
        def __init__(self):
            self.ib = IB()
    
            self.ib.disconnectedEvent += self.on_disconnected_event
            self.ib.connectedEvent += self.on_connected_event
            self.ib.errorEvent += self.on_error_event
            self.ib.timeoutEvent += self.on_timeout_event
    
            self.ib.client.apiError = self.on_api_error
            self.contract = Forex(SYMBOL)
            self.book = Book()
    
        def on_api_error(self, msg: str):
            logger.info(f"[on_api_error] :: {msg} \n "
                        f"Waiting 3 sec before reconnection.")
            asyncio.get_event_loop().call_later(3, self.connect)
    
        def connect(self):
            try:
                self.ib.connect('localhost', 7497, clientId=1)
            except ConnectionRefusedError:
                logger.error("Unable to connect")
                pass
            logger.info(f"Subscribing on book for {SYMBOL}")
            self.ib.qualifyContracts(self.contract)
            ticker = self.ib.reqMktDepth(self.contract)
            ticker.updateEvent += self.on_book_update
    
            logger.info("Waiting for connection to data...")
            self.ib.sleep(2)
    
        def on_connected_event(self):
            logger.info("[on_connected_event]:: IB connected.")
    
        def on_disconnected_event(self):
            logger.info("[on_DISconnected_event]:: IB disconnected.")
    
        def on_error_event(self, reqId: int, errorCode: int, errorString: str,
                           contract: Contract):
           logger.info(f"[on_error_event] :: reqId: {reqId}, errorCode: {errorCode}, "
                        f"{errorString.encode('utf-8').decode()}, contract: {contract}")
    
        def on_timeout_event(self, time_since_last_update: float):
           logger.info(f"[on_timeout_event] :: Last event was {time_since_last_update} ago.")
    
        def on_book_update(self, ticker):
            bids = ticker.domBids
            asks = ticker.domAsks
            if bids is not None and len(bids) > 0 and len(asks) > 0:
                self.book.bid = bids[0].price
                self.book.ask = asks[0].price
    
    ib = IBConnectionModule()
    ib.connect()
    
    is_clearing = False
    
    while True:
        ib.sleep(0.5)
        if ib.book.ask < 0 or ib.book.bid < 0:
            if not is_clearing:
                logger.info(f"End of the current trading session. bid/ask = {ib.book.bid}/{ib.book.ask}")
                is_clearing = True
            continue
        if is_clearing:
            logger.info(f"Start of a new trading session bid/ask = {ib.book.bid}/{ib.book.ask}")
            is_clearing = False`

LOGS:

`2022-09-07 00:00:01,001 INFO :: End of the current trading session. bid/ask = -1.0/-1.0

2022-09-07 00:04:04,908 ERROR :: Error 317, reqId 4: , contract: Forex('EURUSD', exchange='IDEALPRO', localSymbol='EUR.USD', tradingClass='EUR.USD')
2022-09-07 00:04:04,909 INFO :: [on_error_event] :: reqId: 4, errorCode: 317., contract: Forex('EURUSD', exchange='IDEALPRO', localSymbol='EUR.USD', tradingClass='EUR.USD')
2022-09-07 00:04:05,055 INFO :: Warning 2103, reqId -1
2022-09-07 00:04:05,055 INFO :: [on_error_event] :: reqId: -1, errorCode: 2103, contract: None
2022-09-07 00:04:06,267 INFO :: Warning 2104, reqId -1
2022-09-07 00:04:06,267 INFO :: [on_error_event] :: reqId: -1, errorCode: 2104, contract: None
2022-09-07 00:09:05,068 ERROR :: Error 317, reqId 4, contract: Forex('EURUSD', exchange='IDEALPRO', localSymbol='EUR.USD', tradingClass='EUR.USD')
2022-09-07 00:09:05,069 INFO :: [on_error_event] :: reqId: 4, errorCode: 317., contract: Forex('EURUSD',  exchange='IDEALPRO', localSymbol='EUR.USD', tradingClass='EUR.USD')
2022-09-07 00:09:05,211 INFO :: Warning 2103, reqId -1
2022-09-07 00:09:05,211 INFO :: [on_error_event] :: reqId: -1, errorCode: 2103, contract: None
2022-09-07 00:09:05,721 INFO :: Warning 2103, reqId -1
2022-09-07 00:09:05,721 INFO :: [on_error_event] :: reqId: -1, errorCode: 2103, contract: None
2022-09-07 00:09:10,000 INFO :: Warning 2103, reqId -1
2022-09-07 00:09:10,000 INFO :: [on_error_event] :: reqId: -1, errorCode: 2103, contract: None
2022-09-07 00:09:25,279 INFO :: Warning 2103, reqId -1
2022-09-07 00:09:25,280 INFO :: [on_error_event] :: reqId: -1, errorCode: 2103contract: None
2022-09-07 00:09:57,510 INFO :: Warning 2104, reqId -1
2022-09-07 00:09:57,511 INFO :: [on_error_event] :: reqId: -1, errorCode: 2104, contract: None
2022-09-07 00:10:59,961 ERROR :: Error 317, reqId 4, contract: Forex('EURUSD', exchange='IDEALPRO', localSymbol='EUR.USD', tradingClass='EUR.USD')
2022-09-07 00:10:59,962 INFO :: [on_error_event] :: reqId: 4, errorCode: 317, contract: Forex('EURUSD',  exchange='IDEALPRO', localSymbol='EUR.USD', tradingClass='EUR.USD')
2022-09-07 00:11:00,102 INFO :: Warning 2103, reqId -1
2022-09-07 00:11:00,103 INFO :: [on_error_event] :: reqId: -1, errorCode: 2103, contract: None
2022-09-07 00:11:00,103 INFO :: Warning 2104, reqId -1
2022-09-07 00:11:00,103 INFO :: [on_error_event] :: reqId: -1, errorCode: 2104
2022-09-07 00:15:00,274 ERROR :: Error for updateMktDepth:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ib_insync/decoder.py", line 186, in handler
    method(*args)
  File "/usr/local/lib/python3.6/dist-packages/ib_insync/wrapper.py", line 896, in updateMktDepth
    reqId, position, '', operation, side, price, size)
  File "/usr/local/lib/python3.6/dist-packages/ib_insync/wrapper.py", line 909, in updateMktDepthL2
    dom[position] = DOMLevel(price, size, marketMaker)
IndexError: list assignment index out of range
2022-09-07 00:15:00,278 ERROR :: Error for updateMktDepth:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ib_insync/decoder.py", line 186, in handler
    method(*args)
  File "/usr/local/lib/python3.6/dist-packages/ib_insync/wrapper.py", line 896, in updateMktDepth
    reqId, position, '', operation, side, price, size)
  File "/usr/local/lib/python3.6/dist-packages/ib_insync/wrapper.py", line 909, in updateMktDepthL2
    dom[position] = DOMLevel(price, size, marketMaker)
IndexError: list assignment index out of range
2022-09-07 00:15:01,464 ERROR :: Error for updateMktDepth:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ib_insync/decoder.py", line 186, in handler
    method(*args)
  File "/usr/local/lib/python3.6/dist-packages/ib_insync/wrapper.py", line 896, in updateMktDepth
    reqId, position, '', operation, side, price, size)
  File "/usr/local/lib/python3.6/dist-packages/ib_insync/wrapper.py", line 909, in updateMktDepthL2
    dom[position] = DOMLevel(price, size, marketMaker)
IndexError: list assignment index out of range
2022-09-07 00:15:01,501 INFO :: Start of a new trading session. bid/ask = 0.99041/0.99077.

2022-09-07 00:15:28,600 ERROR :: Error for updateMktDepth:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ib_insync/decoder.py", line 186, in handler
    method(*args)
  File "/usr/local/lib/python3.6/dist-packages/ib_insync/wrapper.py", line 896, in updateMktDepth
    reqId, position, '', operation, side, price, size)
  File "/usr/local/lib/python3.6/dist-packages/ib_insync/wrapper.py", line 909, in updateMktDepthL2
    dom[position] = DOMLevel(price, size, marketMaker)
IndexError: list assignment index out of range`

... this error continues till I stop the program

**Comment by erdewit** [comment]
> Can somebody explain step by step how to do auto reconnection in a right way?

I don't think so.

**Comment by renegadephysicist** [comment]
This is what I did:

https://github.com/erdewit/ib_insync/issues/41
