### ISSUE TITLE
Error for pnlSingle

### ISSUE THREAD

**Issue by piotrgolawski** [erdewit/ib_insync#542]
Hi,
I am using 
`ib.reqPnLSingle('account', '', fill.contract.conId)`
and I am receiving:

Error for pnlSingle:
Traceback (most recent call last):
  File "/home/p/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ib_insync/decoder.py", line 185, in handler
    for (typ, field) in zip(types, fields[skip:])]
  File "/home/p/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ib_insync/decoder.py", line 185, in <listcomp>
    for (typ, field) in zip(types, fields[skip:])]
ValueError: invalid literal for int() with base 10: '2.0'

Could you please share the proper way of calculation loss/profit?

**Comment by piotrgolawski** [comment]
I have "fixed" it by "float(field or 0) if typ is float or int else"

`        def handler(fields):
            method = getattr(self.wrapper, methodName, None)
            if method:
                try:
                    args = [
                        field if typ is str else
                        float(field or 0) if typ is float or int else
                        bool(int(field or 0))
                        for (typ, field) in zip(types, fields[skip:])]
                    method(*args)
                except Exception:
                    self.logger.exception(f'Error for {methodName}:')

        return handler`
        
        in decoder.py
        
        
        But still all results are about single conId.
        
        Could you please tell me how can I know which pair of buy-sell transaction gives me a profit?
