### ISSUE TITLE
Error handling fields in reqMatchingSymbols method

### ISSUE THREAD

**Issue by teo-together** [erdewit/ib_insync#548]
` results = ib_gw.reqMatchingSymbols('AAPL')
`
```csharp
`2023-01-23 21:15:43,161 loglevel=ERROR  logger=ib_insync.Decoder interpret() L199  Error handling fields: ['79', '8', '16', '265598', 'AAPL', 'STK', 'NASDAQ', 'USD', '5', 'CFD', 'OPT', 'IOPT', 'WAR', 'BAG', 'APPLE INC', '', '493546048', 'AAPL', 'STK', 'LSEETF', 'GBP', '0', 'LS 1X AAPL', '', '38708077', 'AAPL', 'STK', 'MEXI', 'MXN', '0', 'APPLE INC', '', '273982664', 'AAPL', 'STK', 'EBS', 'CHF', '0', 'APPLE INC', '', '532640894', 'AAPL', 'STK', 'AEQLIT', 'CAD', '0', 'APPLE INC-CDR', '', '242506861', 'AAPLUSD', 'STK', 'EBS', 'USD', '0', 'APPLE INC', '', '290656768', 'NY2LAAPL', 'IND', 'NYSE', 'USD', '0', 'NYSE Leveraged 2X AAPL Index', '', '86792725', 'AVSPY', 'IND', 'NASDAQ', 'USD', '0', 'Nasdaq OMX Alpha AAPL vs. SPY Index', '', '578561422', 'AAPD', 'STK', 'NASDAQ', 'USD', '2', 'OPT', 'BAG', 'DIREXION DAILY AAPL BEAR 1X', '', '578561419', 'AAPU', 'STK', 'NASDAQ', 'USD', '2', 'OPT', 'BAG', 'DIREXION DAILY AAPL BULL 1.5', '', '578561458', 'AAPB', 'STK', 'NASDAQ', 'USD', '1', 'OPT', 'GRANITE 1.75X AAPL DAILY ETF', '', '493546053', 'AAP1', 'STK', 'LSEETF', 'EUR', '0', 'LS 1X AAPL', '', '493546045', '1AAP', 'STK', 'LSEETF', 'USD', '0', 'LS 1X AAPL', '', '-1', '', 'BOND', '', '', '0', 'Apple Inc', 'e1432232', '-1', '', 'BOND', '', '', '0', 'Ascendas Singbridge', 'e3914336', '-1', '', 'BOND', '', '', '0', 'Aarush Phase IV Logistics Park Pvt Ltd', 'e3896693']
Traceback (most recent call last):
  File "/Users/xx/Documents/Git/xx/xx/lib/python3.10/site-packages/ib_insync/decoder.py", line 197, in interpret
    handler(fields)
  File "/Users/xx/Documents/Git/xx/xx/venv/lib/python3.10/site-packages/ib_insync/decoder.py", line 648, in symbolSamples
    c.conId = int(c.conId)
ValueError: invalid literal for int() with base 10: 'APPLE INC'`
```

**Comment by Remonell** [comment]
How did you solve this?
