### ISSUE TITLE
Error handling fields

### ISSUE THREAD

**Issue by Remonell** [erdewit/ib_insync#555]
ib_insync: 0.9.81
TWS: Build 10.20.1f, Dec 13, 2022 4:01:41 PM
Python: 3.11.1

Running the sample code from the readme:
```
from ib_insync import *
# util.startLoop()  # uncomment this line when in a notebook

ib = IB()
ib.connect('127.0.0.1', 7497, clientId=1)

contract = Forex('EURUSD')
bars = ib.reqHistoricalData(
    contract, endDateTime='', durationStr='30 D',
    barSizeSetting='1 hour', whatToShow='MIDPOINT', useRTH=True)

# convert to pandas dataframe:
df = util.df(bars)
print(df)

```

```
Error handling fields: ['17', '3', '20230112 20:19:28 US/Eastern', '20230211 20:19:28 US/Eastern', '718', '20221229 17:15:00  
 US/Eastern', '1.06665', '1.06665', '1.06600', '1.06615', '-1', '-1', '-1', '20221229 18:00:00 US/Eastern', '1.06615', '1.06620',   '1.06545', '1.06605', '-1', '-1', '-1', '20221229 19:00:00 US/Eastern', '1.06605', '1.06685', '1.06590', '1.06685', '-1', '-1', '-1', '20221229 20:00:00 US/Eastern', '1.06685', '1.06695', '1.06570', '1.06605', '-1', '-1', '-1', '20221229 21:00:00 US/Eastern', '1.06605', '1.06605', '1.06550', '1.06585', '-1', '-1', '-1', '20221229 22:00:00 US/Eastern', '1.06585', '1.06635', '1.06575', '1.06590', '-1', '-1', '-1', '20221229 23:00:00 US/Eastern', '1.06590', '1.06595', '1.06520', '1.06555', '-1', '-1', '-1', '20221230 00:00:00 US/Eastern', '1.06555', '1.06580', '1.06425', '1.06435', '-1', '-1', '-1', '20221230 01:00:00 US/Eastern', '1.06435', '1.06505', '1.06410', '1.06445', '-1', '-1', '-1', '20221230 02:00:00 US/Eastern', '1.06445', '1.06515', '1.06385', '1.06510', '-1', '-1', 
removed a bunch of values here
'-1', '20221230 03:00:00 US/Eastern', '1.06510', '1.06745', '1.06500', '1.06710', '-1', '-1', '-1', '20221230 04:00:00 US/Eastern', '1.06710', '1.06715', '1.06515', '1.06550', '-1', '-1', '-1', '20221230 05:00:00 US/Eastern', '1.06550', '1.06765', '1.06535', '1.06695', '-1', '-1', '-1', '20221230 06:00:00 US/Eastern', '1.06695', '1.06995', '1.06695', '1.06760', '-1', '-1', '-1', '20221230 07:00:00 US/Eastern', '1.06760', '1.06880', '1.06715', '1.06725', '-1', '-1', '-1', '20221230 08:00:00 US/Eastern', '1.06725', '1.06805', '1.06455', '1.06690', '-1', '-1', '-1', '20221230 09:00:00 US/Eastern', '1.06690', '1.07010', '1.06615', '1.06885', '-1', '-1', '-1', '20221230 10:00:00 US/Eastern',  '-1', '-1', '20230210 16:00:00 US/Eastern', '1.06790', '1.06800', '1.06735', '1.06740', '-1', '-1', '-1']   
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\zoneinfo\_common.py", line 12, in load_tzdata
    return resources.files(package_name).joinpath(resource_name).open("rb")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\importlib\resources\_common.py", line 22, in files
    return from_package(get_package(package))
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\importlib\resources\_common.py", line 53, in get_package       
    resolved = resolve(package)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\importlib\resources\_common.py", line 44, in resolve
    return cand if isinstance(cand, types.ModuleType) else importlib.import_module(cand)
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tzdata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\ib_insync\decoder.py", line 198, in interpret    
    handler(fields)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\ib_insync\decoder.py", line 469, in historicalData
    self.wrapper.historicalData(int(reqId), bar)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\ib_insync\wrapper.py", line 552, in historicalData
    bar.date = parseIBDatetime(bar.date)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\ib_insync\util.py", line 543, in parseIBDatetime 
    t = t.replace(tzinfo=ZoneInfo(s2))
                         ^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Lib\zoneinfo\_common.py", line 24, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key US/Eastern'
```

**Comment by Remonell** [comment]
Just solved this by manually installing tzdata:
`pip install tzdata`

**Comment by erdewit** [comment]
On what version of Windows is this?
