### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor during IB.__del__.

### ISSUE THREAD

**Issue by Alillystone** [erdewit/ib_insync#561]
Hi, I'm trying to run multiple trading bots on separate event_loop tasks which are run through a `run_forever` as such:

```
# ensure we apply nest_asyncio as we have multiple event loops (Bots + IB).
def main():
    ...
    nest_asyncio.apply()

    # initialise event loop and Bot tasks.
    event_loop = asyncio.get_event_loop()
    for bot_metadata in bots:
        bot_object = Bot(metadata=bot_metadata, connect=True)
        event_loop.create_task(bot_object.run())

    # run event loop (unless Keyboard Interrupted).
    try:
        event_loop.run_forever()
    ...

class Bot(object):
    def __init__(self, metadata: dict, connect: bool):

        # create IB client object (no intrinsic connection created).
        self.client = IB()
        self.client_id = metadata["IB_GATEWAY_CLIENT_ID"]

        # connect to IB server depending on input parameter.
        if connect:
            self.client.connect(
                self.metadata["IB_GATEWAY_ENDPOINT"],
                self.metadata["IB_GATEWAY_PORT"],
                self.client_id
            )
    
    async def execute_management(self, analytic_responses: list, session: ClientSession) -> list:
        """
        Gathers data dependencies from IB client. Uses keepUpToDate where possible. Returns
        the manager response which should just be a list of orders.
        """
        ...
        return managment_response

    async def execute_inference(self, analytic_metadata: dict, session: ClientSession) -> Any:
        """
        Gathers data dependencies from IB client. Uses keepUpToDate where possible. Returns
        the analytic response to be used by the manager.
        """
        ...
        return inference
    
    async def run(self):
        """
        Main entry point for the Bot. Executes all defined analytics for the bot followed
        by the Bot manager. Any orders are passed to IB for placing/updating.
        """

        # initialise an asynchronous client session, used to call analytic
        # endpoints in parallel and join the results.
        async with ClientSession() as session:
  
            # define the analytic tasks and await their execution.
            analytic_tasks = [
                self.execute_inference(...)
                for endpoint in self.metadata["ANALYTIC_ENDPOINTS"]
            ]
            analytic_responses = await asyncio.gather(*analytic_tasks)
  
            # execute manager response asnynchronously use the responses from the
            # analytics. The manager response should always be a list of orders.
            manager_response = await self.execute_management(...)
  
        # pass any resultant orders to IB for execution.
        # (Wrapper function not included for brevity).
        self.place_orders(
            bot_id=self.metadata["BOT_ID"], 
            orders=manager_response
        )
```
This works great for about 1-2 hours (sometimes longer, sometimes shorter), but eventually without fail the program errors with the following traceback:

```
task: <Task pending name='Task-10' coro=<Bot.run() running at /.../bot.py:153> wait_for=<_GatheringFuture pending cb=[Task.__wakeup()]>>
Exception ignored in: <coroutine object Bot.run at 0x10e68bf40>
RuntimeError: coroutine ignored GeneratorExit
Exception ignored in: <function IB.__del__ at 0x10e7203a0>
Traceback (most recent call last):
  File "/.../lib/python3.10/site-packages/ib_insync/ib.py", line 233, in __del__
    self.disconnect()
  File "/.../lib/python3.10/site-packages/ib_insync/ib.py", line 287, in disconnect
    self.client.disconnect()
  File "/.../lib/python3.10/site-packages/ib_insync/client.py", line 232, in disconnect
    self.conn.disconnect()
  File "/.../lib/python3.10/site-packages/ib_insync/connection.py", line 44, in disconnect
    self.transport.write_eof()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 972, in write_eof
    self._sock.shutdown(socket.SHUT_WR)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function IB.__del__ at 0x10e7203a0>
```

I thought that it would be safe running the bots through separate async tasks and separate IB objects and client ids, but clearly there is something consistently strange happening. Any ideas on the above?

Cheers in advance!

**Comment by erdewit** [comment]
The bug here is in asyncio. I've seen it also sometimes and it seems due to the random order in which destructors are called.

As usual it's generally best to use a long-lived API connection, so not connecting and disconnecting al the time.
