### ISSUE TITLE
ib_insync connects to TWS but disconnect on Mac when everything was working the day before

### ISSUE THREAD

**Issue by pmeheut** [erdewit/ib_insync#612]
Everything used to work till yesterday. Now when I'm using ib_insync 0.9.70 or 0.9.86 to connect to TWS 10.23.2a built Jun 15, it connects but fails on a Timeout after a while.
I'm running Python 3.9 on a Mac with Ventura, no changes here.
I have the problem with my real account but it works with the paper trading one.
Any idea?

Using util.logToConsole('DEBUG'), I get:

``
023-07-05 17:05:31,425 ib_insync.client INFO Connecting to localhost:7497 with clientId 201...
2023-07-05 17:05:31,445 ib_insync.client INFO Connected
2023-07-05 17:05:31,479 ib_insync.client DEBUG <<< 176,20230705 17:05:30 Central European Standard Time
2023-07-05 17:05:31,479 ib_insync.client DEBUG >>> 71,2,201,
2023-07-05 17:05:31,479 ib_insync.client INFO Logged on to server version 176
2023-07-05 17:05:31,485 ib_insync.client DEBUG <<< 9,1,1
2023-07-05 17:05:31,485 ib_insync.client DEBUG <<< 15,1,<account_id>
2023-07-05 17:05:31,485 ib_insync.client INFO API connection ready
2023-07-05 17:05:31,485 ib_insync.client DEBUG >>> 61,1
2023-07-05 17:05:31,485 ib_insync.client DEBUG >>> 5,1
2023-07-05 17:05:31,486 ib_insync.client DEBUG >>> 99,0
2023-07-05 17:05:31,486 ib_insync.client DEBUG >>> 6,2,1,<account_id>
2023-07-05 17:05:31,486 ib_insync.client DEBUG >>> 76,1,1,<account_id>,,0
2023-07-05 17:05:31,487 ib_insync.client DEBUG <<< 4,2,-1,2104,Market data farm connection is OK:usfarm.nj,
...
...
2023-07-05 17:05:31,896 ib_insync.client DEBUG <<< 73,1,1,<account_id>,,RealCurrency,EUR,BASE
2023-07-05 17:05:31,896 ib_insync.client DEBUG <<< 73,1,1,<account_id>,,IssuerOptionValue,0.00,BASE
2023-07-05 17:05:31,896 ib_insync.client DEBUG <<< 73,1,1,<account_id>,,Cryptocurrency,,BASE
2023-07-05 17:05:31,896 ib_insync.client DEBUG <<< 74,1,1
2023-07-05 17:05:31,896 ib_insync.client DEBUG >>> 7,3,2,0,,,,,,
2023-07-05 17:05:41,898 ib_insync.ib INFO Disconnecting from localhost:7497, 119 B sent in 8 messages, 12.6 kB received in 263 messages, session time 10.5 s.
2023-07-05 17:05:41,898 ib_insync.client INFO Disconnecting
Traceback (most recent call last):
  File "/Users/pascal/opt/anaconda3/envs/lbo/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
  File "/Users/pascal/opt/anaconda3/envs/lbo/lib/python3.9/asyncio/futures.py", line 196, in result
    raise exc
asyncio.exceptions.CancelledError

**Comment by erdewit** [comment]
> 2023-07-05 17:05:41,898 ib_insync.ib INFO Disconnecting from localhost:7497, 119 B sent in 8 messages, 12.6 kB received in 263 messages, session time 10.5 s.

Looks like a regular disconnect.

**Comment by pmeheut** [comment]
Except its not: it fails on a timeout, the program quits, etc when the exact same code in the exact same environment used to work yesterday.
The end of the message is 
``
Traceback (most recent call last):
  File "/Users/pascal/opt/anaconda3/envs/lbo/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
  File "/Users/pascal/opt/anaconda3/envs/lbo/lib/python3.9/asyncio/futures.py", line 196, in result
    raise exc
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/pascal/opt/anaconda3/envs/lbo/lib/python3.9/site-packages/ib_insync/util.py", line 341, in run
    result = loop.run_until_complete(task)
  File "/Users/pascal/opt/anaconda3/envs/lbo/lib/python3.9/site-packages/nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "/Users/pascal/opt/anaconda3/envs/lbo/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/pascal/opt/anaconda3/envs/lbo/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/pascal/opt/anaconda3/envs/lbo/lib/python3.9/site-packages/ib_insync/ib.py", line 1782, in connectAsync
    await asyncio.wait_for(self.reqExecutionsAsync(), timeout)
  File "/Users/pascal/opt/anaconda3/envs/lbo/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
``
