### ISSUE TITLE
qt_ticker_table.py in examples does not connect

### ISSUE THREAD

**Issue by pmeheut** [erdewit/ib_insync#613]
See https://github.com/erdewit/ib_insync/issues/612 for the context.

When launched, pressing the Connect button generates an exception.
It can be fixed by commenting `await asyncio.wait_for(self.reqExecutionsAsync(), timeout)`line 1782 in ib.py

``
Traceback (most recent call last):
  File "/Users/pascal/opt/anaconda3/envs/ib/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
  File "/Users/pascal/opt/anaconda3/envs/ib/lib/python3.9/asyncio/futures.py", line 196, in result
    raise exc
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pascal/PythonTmp/ib_insync/examples/qt_ticker_table.py", line 89, in onConnectButtonClicked
    self.ib.connect(*self.connectInfo)
  File "/Users/pascal/PythonTmp/ib_insync/ib_insync/ib.py", line 279, in connect
    return self._run(self.connectAsync(
  File "/Users/pascal/PythonTmp/ib_insync/ib_insync/ib.py", line 318, in _run
    return util.run(*awaitables, timeout=self.RequestTimeout)
  File "/Users/pascal/PythonTmp/ib_insync/ib_insync/util.py", line 341, in run
    result = loop.run_until_complete(task)
  File "/Users/pascal/opt/anaconda3/envs/ib/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/Users/pascal/opt/anaconda3/envs/ib/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/pascal/opt/anaconda3/envs/ib/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/pascal/PythonTmp/ib_insync/ib_insync/ib.py", line 1782, in connectAsync
    await asyncio.wait_for(self.reqExecutionsAsync(), timeout)
  File "/Users/pascal/opt/anaconda3/envs/ib/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
python-BaseException
``

**Comment by pmeheut** [comment]
It seems that in some cases, TWS API does not call `execDetailsEnd`after a `reqExecutions`.
So the future has no result, fails on a timeout (I tried with up to 100 seconds) and the connection fails but everything seem to be working fine. I'll do more tests to check if we receive execs anyhow.

**Comment by pmeheut** [comment]
At it does not occurs often, I wonder if this has something to do with bank holidays.
In the mean time, replacing in ib.py connectAsync method
await asyncio.wait_for(self.reqExecutionsAsync(), timeout)
by
reqId = self.client.getReqId() self.client.reqExecutions(reqId, ExecutionFilter())
solves the problem and we still receive the executions of course.
