### ISSUE TITLE
asyncio.exceptions.TimeoutError on mac

### ISSUE THREAD

**Issue by 430scud** [erdewit/ib_insync#620]
im on macbook m1 with TWS running

Last week I was able to run the example code on your project README.

Now I am unable to run it. I am able to connect to the port via telnet.

I also see in the verbose logs that it is able to connect 

im really not sure how to continue here.

```
from ib_insync import *
# util.startLoop()  # uncomment this line when in a notebook

ib = IB()
ib.connect('127.0.0.1', 7497, clientId=1)

contract = Forex('EURUSD')
bars = ib.reqHistoricalData(
    contract, endDateTime='', durationStr='30 D',
    barSizeSetting='1 hour', whatToShow='MIDPOINT', useRTH=True)

# convert to pandas dataframe (pandas needs to be installed):
df = util.df(bars)
print(df)
```

```
(ibkr) user@MacBook-Pro ibkr % python3 test.py 
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user/ib/ibkr/test.py", line 5, in <module>
    ib.connect('127.0.0.1', 7497, clientId=1)
  File "/Users/user/ib/ibkr/lib/python3.10/site-packages/ib_insync/ib.py", line 279, in connect
    return self._run(self.connectAsync(
  File "/Users/user/ib/ibkr/lib/python3.10/site-packages/ib_insync/ib.py", line 318, in _run
    return util.run(*awaitables, timeout=self.RequestTimeout)
  File "/Users/user/ib/ibkr/lib/python3.10/site-packages/ib_insync/util.py", line 341, in run
    result = loop.run_until_complete(task)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/user/ib/ibkr/lib/python3.10/site-packages/ib_insync/ib.py", line 1782, in connectAsync
    await asyncio.wait_for(self.reqExecutionsAsync(), timeout)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
(ibkr) user@MacBook-Pro ibkr % 
```

**Comment by 430scud** [comment]
okay looks ilke im able to connect and pull up balances and portfolio but that timeouterror confused me

but it still fails to bring up that panda table with EURUSD. im confused why that would stop working.

from ib_insync import *
from ib_insync import util
import os
util.logToConsole('DEBUG')

account = str(os.environ.get('IB_LIVE'))
ib = IB()

print('connect ...')
ib.connect('127.0.0.1', 7497, 1, 30)

print('portfolio(): ')
ib.client.reqAccountUpdates(False, account)
ib.reqAccountUpdates(account)

print('balance(): ')
ib.accountValues(account)

**Comment by thisisloze** [comment]
I updated my TWS and now get this error? What did you do to fix it?
