### ISSUE TITLE
Getting Disconnected At Certain Times

### ISSUE THREAD

**Issue by eljefe6a** [erdewit/ib_insync#655]
I'm hitting a weird problem where ib_insync will disconnect immediately. The disconnect seems to happen starting at around 10:00-10:30 AM EST. It disconnects immediately after `ib.connect`. The connection works just fine up to that point in time.

This only happens with TWS and I'm using `build 10.25.1n, Oct 30, 2023 4:01:24 PM` on Linux. If I start using the gateway, everything starts working again. This is annoying as I'm still interacting with TWS.

Here is the connection code:
```
    util.logToConsole('DEBUG')
    util.startLoop()
    ib = IB()
    ib.connect('127.0.0.1', 7496, clientId=13)
```

Here is the last part of `util.logToConsole('DEBUG')`:
```
2023-11-10 16:34:19,087 ib_insync.client DEBUG <<< 73,1,1,*ACCOUNTNUMBER*,,MutualFundValue,0.00,BASE
2023-11-10 16:34:19,087 ib_insync.client DEBUG <<< 73,1,1,*ACCOUNTNUMBER*,,MoneyMarketFundValue,0.00,BASE
2023-11-10 16:34:19,087 ib_insync.client DEBUG <<< 73,1,1,*ACCOUNTNUMBER*,,CorporateBondValue,0.00,BASE
2023-11-10 16:34:19,087 ib_insync.client DEBUG <<< 73,1,1,*ACCOUNTNUMBER*,,TBondValue,0.00,BASE
2023-11-10 16:34:19,087 ib_insync.client DEBUG <<< 73,1,1,*ACCOUNTNUMBER*,,TBillValue,0.00,BASE
2023-11-10 16:34:19,087 ib_insync.client DEBUG <<< 73,1,1,*ACCOUNTNUMBER*,,WarrantValue,0.00,BASE
2023-11-10 16:34:19,087 ib_insync.client DEBUG <<< 73,1,1,*ACCOUNTNUMBER*,,FxCashBalance,0.00,BASE
2023-11-10 16:34:19,087 ib_insync.client DEBUG <<< 73,1,1,*ACCOUNTNUMBER*,,AccountOrGroup,U7327047,BASE
2023-11-10 16:34:19,088 ib_insync.client DEBUG <<< 73,1,1,*ACCOUNTNUMBER*,,RealCurrency,BASE,BASE
2023-11-10 16:34:19,088 ib_insync.client DEBUG <<< 73,1,1,*ACCOUNTNUMBER*,,IssuerOptionValue,0.00,BASE
2023-11-10 16:34:19,088 ib_insync.client DEBUG <<< 73,1,1,*ACCOUNTNUMBER*,,Cryptocurrency,,BASE
2023-11-10 16:34:19,088 ib_insync.client DEBUG <<< 74,1,1
2023-11-10 16:34:19,088 ib_insync.client DEBUG >>> 7,3,2,0,,,,,,
2023-11-10 16:34:23,094 ib_insync.ib INFO Disconnecting from 127.0.0.1:7496, 116 B sent in 8 messages, 16.3 kB received in 311 messages, session time 10.7 s.
2023-11-10 16:34:23,094 ib_insync.client INFO Disconnecting
```

**Comment by eljefe6a** [comment]
I tried the gateway again and fails too. Here is the log from it:
```
023-11-10 16:49:31.127 [XN] INFO  [JTS-EMsgPacer-152] - Process immidiately open orders request: ReqOpenOrders(5) eServer: EServerSocket::[EServer::[m_serverId=13m_clientVersion=176m_subscribedToNews=POPUPm_accountDataRequestCode=m_reader=JTS-EServerSocket-148m_logger=ELogger::[m_logLevel=2]m_logRec=ELogRecord::[m_logLevel=5m_message=m_requestMsgType=0m_responseMsgType=0m_bReset=truem_nestedException=null]]m_socket=4002m_dis=Setm_dos=Setm_data=Setm_writer=EWriter::[Thread[JTS-EWriter3-150,6,main]s_threadNo=4m_data=Setm_outputStream=Set]
2023-11-10 16:49:31.227 [XN] INFO  [JTS-EMsgPacer-152] - Sending completed orders request for serverId=13 ...
2023-11-10 16:49:31.229 [XN] INFO  [JTS-ActivityBus-48] - Schedule Query completed orders for 20231110
2023-11-10 16:49:31.231 [XN] INFO  [JTS-CompletedOrdersQuery-153] - Query completed orders for:20231110
2023-11-10 16:49:31.327 [XN] INFO  [JTS-EMsgPacer-152] - Starting compressor
2023-11-10 16:49:31.327 [XN] INFO  [JTS-EMsgPacer-152] - Shutting down compressor. FlatLen:0
2023-11-10 16:49:31.327 [XN] INFO  [JTS-EMsgPacer-152] - CM setting requested API account spec to *ACCOUNTNUMBER*.(API)
2023-11-10 16:49:31.327 [XN] INFO  [JTS-EMsgPacer-152] - CM Sending current account image *ACCOUNTNUMBER* to API
2023-11-10 16:49:31.360 [XN] INFO  [JTS-CCPDispatcherS4-51] - Received live orders end marker session:4
2023-11-10 16:49:31.361 [XN] INFO  [JTS-CCPDispatcherS4-51] - Intelligent order recovery: notify mgr, sessionID=4
2023-11-10 16:49:31.361 [XN] INFO  [JTS-ActivityBus-48] - Received 0 completed order(s) for serverId=13
2023-11-10 16:49:31.429 [XN] INFO  [JTS-EMsgPacer-152] - LOG Client 13 Output exceeded limit (was: 100009), removed first half
2023-11-10 16:49:32.031 [XN] INFO  [JTS-usfarm.njDispatcherS10-119S10-120] - Sending for ticker=4 market data info: bboExchangeAndSecType=null, snapshot perms=IRRELEVANT.
2023-11-10 16:49:32.494 [XN] INFO  [JTS-AsyncNonLocked-46] - Return lazy parametermap for OPT expiryRange: from: ?to: ? strikeRange: all filters: []
2023-11-10 16:49:32.494 [XN] INFO  [JTS-AsyncNonLocked-46] - no rule for id=110
2023-11-10 16:49:32.632 [XN] INFO  [JTS-EServerSocket-148] - [13:176:176:1:0:0:0:ERR] Socket connection for client{13} has closed. 
2023-11-10 16:49:32.632 [XN] INFO  [JTS-EServerSocket-148] - Connection terminated
2023-11-10 16:49:32.633 [XN] INFO  [JTS-EServerSocket-148] - Cleaning up [serverId: 13]...
2023-11-10 16:49:32.633 [XN] INFO  [JTS-EServerSocketNotifier-149] - Terminating async queue thread
2023-11-10 16:49:32.633 [XN] INFO  [JTS-EServerSocket-148] - Cleaning up [serverId: 13]...
2023-11-10 16:49:32.633 [XN] INFO  [JTS-EServerSocket-148] - Cleaning up [serverId: 13]...
2023-11-10 16:49:32.633 [XN] INFO  [JTS-EServerSocket-148] - ArEServer: Removing 327973838 with id 13
2023-11-10 16:49:32.633 [XN] INFO  [JTS-EServerSocket-148] - eServersChanged: 0
2023-11-10 16:49:32.633 [XN] INFO  [JTS-EServerSocket-148] - ============ EServerSocket messages stats ============
2023-11-10 16:49:32.634 [XN] INFO  [JTS-EServerSocket-148] - Number of socket messages pushed to updates queue: 1
2023-11-10 16:49:32.634 [XN] INFO  [JTS-EServerSocket-148] - Number of socket messages sent directly: 60
2023-11-10 16:49:32.634 [XN] INFO  [JTS-EServerSocket-148] - =======================================================
2023-11-10 16:49:32.634 [XN] INFO  [JTS-EServerSocket-148] - There are no API orders being processed.
2023-11-10 16:49:32.634 [XN] INFO  [JTS-EServerSocket-148] - SecDefRequestTimeOut: There are no timed out SecDef requests.
2023-11-10 16:49:32.634 [XN] INFO  [JTS-EServerSocket-148] - UnhandledOrderPresetRequest: There are no unprocessed order preset requests.
2023-11-10 16:49:32.634 [XN] INFO  [JTS-EWriter3-150] - [13:176:176:1:0:0:0:SYS] Writer thread terminated for socket client{13}.
2023-11-10 16:49:32.634 [XN] INFO  [JTS-EServerSocket-148] - [13:176:176:1:0:0:0:SYS] Ending conversation with client{13} at 127.0.0.1
2023-11-10 16:49:51.318 [XN] INFO  [JTS-Cleaner-50] - market data wrapper, cleaning maps
2023-11-10 16:49:51.318 [XN] INFO  [JTS-Cleaner-50] - Start orphan ecs cleaning (force=false). Total orphan ecs to remove: 1
2023-11-10 16:49:51.319 [XN] INFO  [JTS-OrphanEcsCleaner-159] - Stop orphan ecs cleaning (force=false). Cleaned 0 of 1 orphan ecs.
2023-11-10 16:49:52.890 [XN] INFO  [JTS-CCPDispatcherS4-51] - Setting time offset to -890 diff -289
2023-11-10 16:49:52.890 [XN] INFO  [JTS-CCPDispatcherS4-51] - CCP reported time: 2023-11-10 16:49:52.000 (GMT) [1699634992000], local time: 2023-11-10 16:49:52.890 (GMT), local time: 2023-11-10 16:49:52.890 (WET), difference in seconds: -0.890, handling delta:0 [Msg1]
```

**Comment by eljefe6a** [comment]
I spent some more time debugging this issue. The exception happens in `ib.py` at:
```
await asyncio.wait_for(self.reqExecutionsAsync(), timeout)
```

The exception is:
```
Unable to display children:Error resolving variables Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/futures.py", line 198, in result
    raise exc
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jesse/repos/stocks/pytrader/venv/lib/python3.11/site-packages/ib_insync/ib.py", line 1782, in connectAsync
    await asyncio.wait_for(self.reqExecutionsAsync(), timeout)
  File "/usr/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jesse/pycharm-community-2023.2.3/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_resolver.py", line 213, in resolve
    return dict[key]
           ~~~~^^^^^
KeyError: 'BaseException'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jesse/pycharm-community-2023.2.3/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 1245, in do_it
    _typeName, val_dict = pydevd_vars.resolve_compound_variable_fields(self.thread_id, self.frame_id, self.scope, self.attributes, dbg.get_user_type_renderers())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jesse/pycharm-community-2023.2.3/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_vars.py", line 301, in resolve_compound_variable_fields
    var = getVariable(thread_id, frame_id, scope, attrs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jesse/pycharm-community-2023.2.3/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_vars.py", line 242, in getVariable
    var = resolver.resolve(var, k)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jesse/pycharm-community-2023.2.3/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_resolver.py", line 215, in resolve
    return getattr(dict, key)
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'BaseException'
```

**Comment by tbrand** [comment]
Same here. Does anyone have an idea for us?

**Comment by lgbongiolo** [comment]
Changing the TWS version to Stable fixed the issue for me.
