### ISSUE TITLE
Exception in ibgatway / tws thrown when trying ib.connect() to simulated IB account

### ISSUE THREAD

**Issue by vanzabee** [erdewit/ib_insync#86]
Below is the ibgateway log

2018-08-05 00:46:50.122 [YB] INFO  [JTS-CCPDispatcherS2-33] - Setting time offset to -4122 diff -304
2018-08-05 00:46:50.123 [YB] INFO  [JTS-CCPDispatcherS2-33] - CCP reported time: 2018-08-04 16:46:46.000 (GMT) [1533401206000], local time: 2018-08-04 16:46:50.122 (GMT), local time: 2018-08-05 00:46:50.122 (CST), difference in seconds: -4.122, handling delta:n/a [Msg1]
2018-08-05 00:46:58.379 [YB] INFO  [JTS-SocketListener-48] - State: HEADER, IsAPI: UNKNOWN
2018-08-05 00:46:58.379 [YB] INFO  [JTS-SocketListener-48] - State: STOP, IsAPI: YES
2018-08-05 00:46:58.396 [YB] INFO  [JTS-SocketListener-48] - ArEServer: Adding 184106552 with id 2147483647
2018-08-05 00:46:58.397 [YB] INFO  [JTS-SocketListener-48] - eServersChanged: 3
2018-08-05 00:46:58.399 [YB] INFO  [JTS-EServerSocketNotifier-86] - Starting async queue thread
2018-08-05 00:46:58.405 [YB] INFO  [JTS-EServerSocket-85] - [2147483647:142:142:1:0:0:0:SYS] Starting new conversation with client on 127.0.0.1
2018-08-05 00:46:58.406 [YB] INFO  [JTS-EServerSocket-85] - [2147483647:142:142:1:0:0:0:SYS] Server version is 142
2018-08-05 00:46:58.406 [YB] INFO  [JTS-EServerSocket-85] - [2147483647:142:142:1:0:0:0:SYS] Client version is 142
2018-08-05 00:46:58.407 [YB] INFO  [JTS-EServerSocket-85] - [2147483647:142:142:1:0:0:0:SYS] is 3rdParty true
2018-08-05 00:46:58.414 [YB] INFO  [JTS-EServerSocket-85] - Start API message, ClientID=12
2018-08-05 00:46:58.429 [YB] INFO  [JTS-EServerSocket-85] - sendMissingSecDefRequests: Num missing = 0
2018-08-05 00:46:58.443 [YB] ERROR [JTS-EServerSocket-85] - [12:142:142:1:0:0:0:ERR] jextend.a9.D(a9.java:153)
java.lang.NullPointerException
	at jextend.a9.D(a9.java:153)
	at jextend.a9.k(a9.java:102)
	at jextend.a8.o(a8.java:482)
	at jextend.dC.a(dC.java:2339)
	at jextend.dC.aY(dC.java:2552)
	at jextend.dC.run(dC.java:2075)
	at java.lang.Thread.run(Unknown Source)

it seems that Position info were being requested by the ib client: 
00:46:54:319 <- 76-1-2-DU******--0-
00:47:24:316 -> ---04-2--1-2151-Positions info is not available yet-

**Comment by vanzabee** [comment]
The call to ib.connect('127.0.0.1', 4002, clientId=12) never returns.  I guess it was waiting for the gateway for some return value?

**Comment by erdewit** [comment]
From the logging it seems that the positions can not be synchronized (this happens during the ib.connect() call). I have never seen that happen but it's probably a weekend thing, the IB servers are wonky then. Try again some other time.
